server.port=8080
spring.application.name=fintwin-backend
spring.data.mongodb.uri=mongodb+srv://SpringBootProject:Spring6970@spring.ml8ubne.mongodb.net/fintwin?retryWrites=true&w=majority&appName=SPRING
